### ISSUE TITLE
Also does this thing even work anymore? AWS blocking inbound AND outbound 25 on EC2.

### ISSUE THREAD

**Issue by JohnDeeBDD** [rioastamal/lightsail-miab-installer#2]
The reason I'm here is because I had MIAB running just fine on EC2. AWS is now blocking outbound AND inbound on port 25. It used to be just blocking outbound. Are these lightsail servers even allowed to accept inbound 25? It seams they REALLY want me to pay to receive email.

**Comment by sulaimangari** [comment]
Yes, they actually blocked port 25 by default. To have access you must submit your valid use case to this [link](https://repost.aws/knowledge-center/lightsail-port-25-throttle). They will emailed you their response and you can have discussion further about your use case with their support team. I already tried this methode twice and failed because my account has bad billing history.

**Comment by rioastamal** [comment]
@JohnDeeBDD I can confirm that my Lighstail and EC2 instance still able to accept inbound connection port 25. Double check your security group settings or OS firewall.
